# Generated by Django 4.1.8 on 2023-04-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
    ]
